title: RegCheck 2024
description: Das Projekt RegCheck 2024 wird durch die ]init[ AG und das Thüringer Finanziministerium durchgeführt.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
